version: '3'
services:
  xplog_collector:
    build:
      context: XPLOG_Collector/
    container_name: XPLOG_COLLECTOR
    hostname: xlp_server
    ports:
      - "8086:8086"
    restart: always
    volumes:
      - ./Collector_logs:/app/logs
