global:
  scrape_interval: 5s
  evaluation_interval: 15s

scrape_configs:
- job_name: 'prometheus'
  static_configs:
  - targets: ['<Manager-IP>:9092']

- job_name: 'cadvisor'
  static_configs:
  - targets:
    - '<Worker1_IP>:9091'
    - '<Worker2_IP>:9091'
    # relabel_configs:
    # - source_labels: [__meta_docker_container_label_com_mycompany_role]
    #   regex: cadvisor
    #   action: drop

- job_name: 'node_exporter'
  static_configs:
  - targets:
    - '<Worker1_IP>:9091'
    - '<Worker2_IP>:9091'
  # relabel_configs:
  # - source_labels: [__meta_docker_container_label_com_mycompany_role]
  #   regex: node_exporter
  #   action: drop

