#ifndef __SYSCALL_H
#define __SYSCALL_H

#define APP 100000

#define SYSCALL_READ                   0
#define SYSCALL_WRITE                  1
#define SYSCALL_OPEN                   2
#define SYSCALL_CLOSE                  3
#define SYSCALL_FSTAT                  5
#define SYSCALL_LSEEK                  8
#define SYSCALL_MMAP                   9
#define SYSCALL_MPROTECT               10
#define SYSCALL_RT_SIGRETURN           15
#define SYSCALL_IOCTL                  16
#define SYSCALL_PREAD64                17
#define SYSCALL_PWRITE64               18
#define SYSCALL_READV                  19
#define SYSCALL_WRITEV                 20
#define SYSCALL_DUP                    32
#define SYSCALL_DUP2                   33
#define SYSCALL_SOCKET                 41
#define SYSCALL_CONNECT                42
#define SYSCALL_ACCEPT                 43
#define SYSCALL_SENDTO                 44
#define SYSCALL_RECVFROM               45
#define SYSCALL_SENDMSG                46
#define SYSCALL_RECVMSG                47
#define SYSCALL_SHUTDOWN               48
#define SYSCALL_BIND                   49
#define SYSCALL_LISTEN                 50
#define SYSCALL_GETSOCKNAME            51
#define SYSCALL_GETPEERNAME            52
#define SYSCALL_SETSOCKOPT             54
#define SYSCALL_GETSOCKOPT             55
#define SYSCALL_CLONE                  56
#define SYSCALL_FORK                   57
#define SYSCALL_VFORK                  58
#define SYSCALL_EXECVE                 59
#define SYSCALL_EXIT                   60
#define SYSCALL_FCNTL                  72
#define SYSCALL_FLOCK                  73
#define SYSCALL_FSYNC                  74
#define SYSCALL_FDATASYNC              75
#define SYSCALL_FTRUNCATE              77
#define SYSCALL_GETDENTS               78
#define SYSCALL_FCHDIR                 81
#define SYSCALL_FCHMOD                 91
#define SYSCALL_FCHOWN                 93
#define SYSCALL_FSTATFS                138
#define SYSCALL_READAHEAD              187
#define SYSCALL_FSETXATTR              190
#define SYSCALL_FGETXATTR              193
#define SYSCALL_FLISTXATTR             196
#define SYSCALL_FREMOVEXATTR           199
#define SYSCALL_GETDENTS64             217
#define SYSCALL_FADVISE64              221
#define SYSCALL_EXIT_GROUP             231
#define SYSCALL_EPOLL_WAIT             232
#define SYSCALL_EPOLL_CTL              233
#define SYSCALL_INOTIFY_ADD_WATCH      254
#define SYSCALL_INOTIFY_RM_WATCH       255
#define SYSCALL_OPENAT                 257
#define SYSCALL_MKDIRAT                258
#define SYSCALL_MKNODAT                259
#define SYSCALL_FCHOWNAT               260
#define SYSCALL_FUTIMESAT              261
#define SYSCALL_NEWFSTATAT             262
#define SYSCALL_UNLINKAT               263
#define SYSCALL_SYMLINKAT              266
#define SYSCALL_READLINKAT             267
#define SYSCALL_FCHMODAT               268
#define SYSCALL_FACCESSAT              269
#define SYSCALL_SYNC_FILE_RANGE        277
#define SYSCALL_VMSPLICE               278
#define SYSCALL_UTIMENSAT              280
#define SYSCALL_EPOLL_PWAIT            281
#define SYSCALL_SIGNALFD               282
#define SYSCALL_FALLOCATE              285
#define SYSCALL_TIMERFD_SETTIME        286
#define SYSCALL_TIMERFD_GETTIME        287
#define SYSCALL_ACCEPT4                288
#define SYSCALL_SIGNALFD4              289
#define SYSCALL_DUP3                   292
#define SYSCALL_PREADV                 295
#define SYSCALL_PWRITEV                296
#define SYSCALL_PERF_EVENT_OPEN        298
#define SYSCALL_RECVMMSG               299
#define SYSCALL_NAME_TO_HANDLE_AT      303
#define SYSCALL_OPEN_BY_HANDLE_AT      304
#define SYSCALL_SYNCFS                 306
#define SYSCALL_SENDMMSG               307
#define SYSCALL_SETNS                  308
#define SYSCALL_FINIT_MODULE           313
#define SYSCALL_EXECVEAT               322
#define SYSCALL_PREADV2                327
#define SYSCALL_PWRITEV2               328
#define SYSCALL_PKEY_MPROTECT          329
#define SYSCALL_STATX                  332
#define SYSCALL_PIDFD_SEND_SIGNAL      424
#define SYSCALL_IO_URING_ENTER         426
#define SYSCALL_IO_URING_REGISTER      427
#define SYSCALL_OPEN_TREE              428
#define SYSCALL_FSCONFIG               431
#define SYSCALL_FSMOUNT                432
#define SYSCALL_FSPICK                 433
#define SYSCALL_OPENAT2                437
#define SYSCALL_FACCESSAT2             439
#define SYSCALL_PROCESS_MADVISE        440
#define SYSCALL_EPOLL_PWAIT2           441
#define SYSCALL_MOUNT_SETATTR          442
#define SYSCALL_QUOTACTL_FD            443
#define SYSCALL_LANDLOCK_ADD_RULE      445
#define SYSCALL_LANDLOCK_RESTRICT_SELF 446
#define SYSCALL_PROCESS_MRELEASE       448

#endif